"""
Django settings for studyCMS project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6-%qz$f^t@)$@fyq^-m!l#!hyb%8nx63ncc0zz9f$b42(#q+ub'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my modification
    'corsheaders',
    'rest_framework',
    # 'myapp',
    'myapp.apps.MyappConfig',
]

AUTH_USER_MODEL = 'myapp.User'


# # Past by me
# from pathlib import Path
# from datetime import timedelta
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
#     "AUTH_HEADER_TYPES": ("Bearer",),
# }


from datetime import timedelta

SIMPLE_JWT = {
    # ── Token Lifetime ────────────────────────────────────────────────
    "ACCESS_TOKEN_LIFETIME":  timedelta(minutes=3000),  # ← short lived
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),      # ← long lived

    # ── Refresh Behavior ──────────────────────────────────────────────
    "ROTATE_REFRESH_TOKENS":    True,   # ← gives new refresh token on every refresh
    "BLACKLIST_AFTER_ROTATION": True,   # ← old refresh token becomes invalid

    # ── Token Type ────────────────────────────────────────────────────
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),

    # ── Algorithm ─────────────────────────────────────────────────────
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    # ── Token Claims ──────────────────────────────────────────────────
    "UPDATE_LAST_LOGIN": True,   # ← updates last_login in DB on each login
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# Cloudinary credentials
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': 'duu0haqtl',     # ← replace
#     'API_KEY':    '752526498282672',        # ← replace
#     'API_SECRET': 'WuXcFpYor3aB4CsKt5am8hoKsnI',     # ← replace
# }


import os

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
DEFAULT_FILE_STORAGE = 'myapp.Utils.pdf_storage.PDFAwareCloudinaryStorage'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://studycms.netlify.app"
]

APPEND_SLASH = False
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studyCMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studyCMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


import dj_database_url
import os

from dotenv import load_dotenv

load_dotenv()
DATABASES = {
    "default": dj_database_url.parse(os.getenv("DATABASE_URL"))
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Email Configuration (Gmail SMTP) ─────────────────────────────────
EMAIL_BACKEND        = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST           = 'smtp.gmail.com'
EMAIL_PORT           = 587
EMAIL_USE_TLS        = True
EMAIL_HOST_USER      = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD  = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL   = os.getenv('EMAIL_HOST_USER', 'noreply@studycms.com')

# ── Celery Configuration ──────────────────────────────────────────────
CELERY_BROKER_URL         = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND     = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT     = ['json']
CELERY_TASK_SERIALIZER    = 'json'
CELERY_RESULT_SERIALIZER  = 'json'
CELERY_TIMEZONE           = 'UTC'
CELERY_TASK_ALWAYS_EAGER  = False  # Set True only for testing without Redis

# ── Add OTP app to installed apps ────────────────────────────────────
INSTALLED_APPS += ['django_celery_results']
