# Generated by Django 4.2.29 on 2026-03-12 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Consultant currently assigned to this student', limit_choices_to={'role': 'consultant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='Consultant who referred this student', limit_choices_to={'role': 'consultant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
