# Generated by Django 4.2.29 on 2026-03-12 18:25

from django.db import migrations, models
import myapp.Utils.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_assigned_to_user_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=myapp.Utils.storage_utils.get_storage, upload_to='study_cms/profile_pics/'),
        ),
    ]
