# Generated by Django 4.2.29 on 2026-03-12 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic_front', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('cnic_back', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('father_cnic_front', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('father_cnic_back', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('passport_page1', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('passport_page2', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('b_form_front', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('b_form_back', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('domicile', models.FileField(blank=True, null=True, upload_to='study_cms/identity/')),
                ('matric_degree_front', models.FileField(blank=True, null=True, upload_to='study_cms/matric/')),
                ('matric_degree_back', models.FileField(blank=True, null=True, upload_to='study_cms/matric/')),
                ('matric_result_card_front', models.FileField(blank=True, null=True, upload_to='study_cms/matric/')),
                ('matric_result_card_back', models.FileField(blank=True, null=True, upload_to='study_cms/matric/')),
                ('matric_institute', models.CharField(blank=True, max_length=255, null=True)),
                ('matric_year', models.CharField(blank=True, max_length=10, null=True)),
                ('matric_description', models.TextField(blank=True, null=True)),
                ('inter_degree_front', models.FileField(blank=True, null=True, upload_to='study_cms/inter/')),
                ('inter_degree_back', models.FileField(blank=True, null=True, upload_to='study_cms/inter/')),
                ('inter_result_card_front', models.FileField(blank=True, null=True, upload_to='study_cms/inter/')),
                ('inter_result_card_back', models.FileField(blank=True, null=True, upload_to='study_cms/inter/')),
                ('inter_institute', models.CharField(blank=True, max_length=255, null=True)),
                ('inter_year', models.CharField(blank=True, max_length=10, null=True)),
                ('inter_description', models.TextField(blank=True, null=True)),
                ('bs_degree_front', models.FileField(blank=True, null=True, upload_to='study_cms/bs/')),
                ('bs_degree_back', models.FileField(blank=True, null=True, upload_to='study_cms/bs/')),
                ('bs_transcript_front', models.FileField(blank=True, null=True, upload_to='study_cms/bs/')),
                ('bs_transcript_back', models.FileField(blank=True, null=True, upload_to='study_cms/bs/')),
                ('bs_institute', models.CharField(blank=True, max_length=255, null=True)),
                ('bs_year', models.CharField(blank=True, max_length=10, null=True)),
                ('bs_description', models.TextField(blank=True, null=True)),
                ('ms_degree_front', models.FileField(blank=True, null=True, upload_to='study_cms/ms/')),
                ('ms_degree_back', models.FileField(blank=True, null=True, upload_to='study_cms/ms/')),
                ('ms_transcript_front', models.FileField(blank=True, null=True, upload_to='study_cms/ms/')),
                ('ms_transcript_back', models.FileField(blank=True, null=True, upload_to='study_cms/ms/')),
                ('ms_institute', models.CharField(blank=True, max_length=255, null=True)),
                ('ms_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ms_description', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='study_cms/professional/')),
                ('ielts_pte', models.FileField(blank=True, null=True, upload_to='study_cms/professional/')),
                ('ielts_pte_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ielts_pte_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_cms/professional/')),
                ('referee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_letters', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reference_letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_cms/other/')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_other_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_cms/professional/')),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_letters', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_experience_letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
