# Generated by Django 4.2.29 on 2026-03-12 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studentdocument_referenceletter_otherdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('university_portal_link', models.URLField(blank=True, null=True)),
                ('portal_login_id', models.CharField(blank=True, max_length=255, null=True)),
                ('portal_login_password', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_name', models.CharField(max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('apply_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_date_to_apply', models.DateField(blank=True, null=True)),
                ('last_date_fee_submit', models.DateField(blank=True, null=True)),
                ('expected_offer_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('under_review', 'Under Review'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('enrolled', 'Enrolled')], default='draft', max_length=20)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='study_cms/applications/offer_letters/')),
                ('fee_slip', models.FileField(blank=True, null=True, upload_to='study_cms/applications/fee_slips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='myapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='study_cms/applications/extra/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='myapp.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
