# Generated by Django 4.2.29 on 2026-04-03 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_chat_and_doc_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceletter',
            old_name='organization',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='otherdocument',
            old_name='document_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='referenceletter',
            old_name='referee_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='experienceletter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experienceletter',
            name='year',
        ),
        migrations.RemoveField(
            model_name='otherdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='otherdocument',
            name='year',
        ),
        migrations.RemoveField(
            model_name='referenceletter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='referenceletter',
            name='year',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='broadcast_target',
            field=models.CharField(blank=True, choices=[('students', 'All Students'), ('consultants', 'All Consultants'), ('everyone', 'Everyone'), ('my_students', 'My Students')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experienceletter',
            name='file',
            field=models.FileField(upload_to='study_cms/experience/'),
        ),
        migrations.AlterField(
            model_name='experienceletter',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='experience_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherdocument',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='other_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referenceletter',
            name='file',
            field=models.FileField(upload_to='study_cms/reference/'),
        ),
        migrations.AlterField(
            model_name='referenceletter',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reference_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
